version: '3.8'

services:
  api_gateway:
    build:
        context: ./api_gateway
        dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - auth_service
      - database_service
      - emotions_service
      - meditation_service
      - profile_service
      - social_service
      - trainings_service

  auth_service:
    build:
        context: ./services/auth_service
        dockerfile: ./Dockerfile_Auth
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://mindmentor:postgres@database_service:5432/mindmentor?sslmode=disable
    depends_on:
      - database_service

  database_service:
    build:
      context: ./
      dockerfile: ./Dockerfile_Database
    ports:
      - "5432:5432"

  emotions_service:
    build:
      context: ./
      dockerfile: ./Dockerfile_Emotions
    ports:
      - "8082:8082"
    depends_on:
      - database_service

  meditation_service:
    build:
      context: ./
      dockerfile: ./Dockerfile_Meditation
    ports:
      - "8083:8083"
    depends_on:
      - database_service

  profile_service:
    build:
      context: ./
      dockerfile: ./Dockerfile_Profile
    ports:
      - "8086:8086"
    depends_on:
      - database_service

  social_service:
    build:
      context: ./
      dockerfile: ./Dockerfile_Social
    ports:
      - "8084:8084"
    depends_on:
      - database_service

  trainings_service:
    build:
      context: ./
      dockerfile: ./Dockerfile_Trainings
    ports:
      - "8085:8085"
    depends_on:
      - database_service