# Используем образ Golang в качестве базового образа
FROM golang:latest as builder



# Копируем файлы проекта в рабочую директорию контейнера
WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY services/trainings_service .

# Сборка бинарного файла микросервиса
RUN go build -o trainings_service .

# Окончательный образ, минимизированный и без лишних зависимостей
FROM alpine:latest

# Копируем бинарный файл из предыдущего образа в окончательный образ
COPY --from=builder /app/trainings-service /usr/local/bin/trainings_service

# Запуск микросервиса при запуске контейнера
CMD ["trainings-service"]
