# Используем образ Golang в качестве базового образа
FROM golang:latest as builder

# Установка переменной окружения GO111MODULE в значение on
ENV GO111MODULE=on

# Копируем файлы проекта в рабочую директорию контейнера
WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY services/emotions_service .

# Сборка бинарного файла микросервиса
RUN go build -o emotions_service .

# Окончательный образ, минимизированный и без лишних зависимостей
FROM alpine:latest

# Копируем бинарный файл из предыдущего образа в окончательный образ
COPY --from=builder /app/emotions-service /usr/local/bin/emotions_service

# Запуск микросервиса при запуске контейнера
CMD ["emotions-service"]
